baseURL = 'https://bluez.org/'
languageCode = 'en-us'
title = 'BlueZ - Official Linux Bluetooth Protocol Stack'

[params]
  description = 'BlueZ is the official Linux Bluetooth protocol stack. It is flexible, efficient and uses a modular implementation.'
  copyrightYearStart = 2001
  copyrightYearEnd = 2025

[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
